export const ENDPOINTS = {
    AUTH: {
        BASE: '/auth/v1',
        LOGIN: '/auth/v1/login',
        REGISTER: '/auth/v1/register',
        REFRESH: '/auth/v1/refresh',
        LOGOUT: '/auth/v1/logout',
        USER: '/auth/v1/user',
    },
    CASHFLOW: {
        BASE: '/cashflow',
        HOUSEHOLDS: '/cashflow/households',
        HOUSEHOLD: (id) => `/cashflow/households/household/${id}`,
        HOUSEHOLD_MEMBERS: '/cashflow/households/household-members/household-member',
        BUDGETS: '/cashflow/households/budgets/budget',
        DEPOSITS: '/cashflow/households/deposits/deposit',
        EXPENSES: '/cashflow/households/expenses/expense',
        EXPENSE_SEARCH: '/cashflow/households/expenses/expense/search',
        CATEGORIES: '/cashflow/categories/category/search',
        DASHBOARD: '/cashflow/dashboard',
        HOUSEHOLD_DASHBOARD: '/cashflow/dashboard/household',
        HOUSEHOLD_ANALYTICS_CORE: '/cashflow/households/analytics/core',
        HOUSEHOLD_ANALYTICS_BEHAVIOR: '/cashflow/households/analytics/behavior',
        HOUSEHOLD_ANALYTICS_DIAGNOSTIC: '/cashflow/households/analytics/diagnostic',
        HOUSEHOLD_ANALYTICS_PLANNING: '/cashflow/households/analytics/planning',
    },
    FITMATE: {
        BASE: '/fitmate',
        EXERCISES: '/fitmate/exercises',
        EXERCISE: (id) => `/fitmate/exercises/exercise/${id}`,
        ROUTINES: '/fitmate/routines',
        ROUTINE: (id) => `/fitmate/routines/routine/${id}`,
        LOGS: '/fitmate/routines/routine/log',
        BODY_PARTS: '/fitmate/bodyparts',
        DRILLS: '/fitmate/drills',
        ANALYTICS_OVERALL: '/fitmate/analytics/overall',
        ANALYTICS_EXERCISE: '/fitmate/analytics/exercise',
        ANALYTICS_WORKOUT_TRENDS: '/fitmate/analytics/workout-trends',
        ANALYTICS_BODY_PART_VOLUME: '/fitmate/analytics/body-part-workout-volume',
        ANALYTICS_MOST_FREQUENT_EXERCISES: '/fitmate/analytics/most-frequent-exercises',
        ANALYTICS_ROUTINE_DISTRIBUTION: '/fitmate/analytics/routine-distribution',
        ANALYTICS_EXERCISE_PROGRESSIONS: '/fitmate/analytics/exercise-progressions',
        ANALYTICS_ROUTINE_EFFICIENCY: '/fitmate/analytics/routine-efficiency',
        ANALYTICS_ACTIVITY_CONSISTENCY: '/fitmate/analytics/activity-consistency',
        ANALYTICS_CALORIES_DURATION: '/fitmate/analytics/calories-duration',
    },
    LEXIMENTOR: {
        BASE: '/leximentor',
        DRILLS: '/leximentor/drill/metadata',
        CHALLENGES: '/leximentor/drill/metadata/challenges',
        CHALLENGE: (id) => `/leximentor/drill/metadata/challenges/challenge/${id}`,
        TTS: '/tts/text2speech',
    },
    SYNAPSTER: {
        BASE: '/synapster',
        SUBJECTS: '/synapster/v1/subjects',
        SUBJECT: (id) => `/synapster/v1/subjects/subject/${id}`,
        CREATE_SUBJECT: '/synapster/v1/subjects/subject',
    },
    WRITEWISE: {
        BASE: '/writewise',
        TOPICS: '/writewise/topics',
    }
};
